import frappe
from frappe.tests import IntegrationTestCase

from frappe_whatsapp_evo.frappe_whatsapp_evo.doctype.evolution_api_settings.evolution_api_settings import (
	find_line,
	get_available_lines_for_user,
	get_line,
	is_line_permitted,
)


def _add_line(instance_name, **kwargs):
	settings = frappe.get_single("Evolution API Settings")
	row = settings.append(
		"evo_lines",
		{
			"base_url": "https://evo.example.com",
			"instance_name": instance_name,
			"api_key": "test-api-key",
			**kwargs,
		},
	)
	settings.save(ignore_permissions=True)
	return row.name


def _restrict_line(instance_name, user):
	settings = frappe.get_single("Evolution API Settings")
	settings.append("line_restrictions", {"line": instance_name, "user": user})
	settings.save(ignore_permissions=True)


class TestEvolutionAPISettings(IntegrationTestCase):
	def tearDown(self):
		settings = frappe.get_single("Evolution API Settings")
		settings.line_restrictions = [r for r in settings.line_restrictions if not r.line.startswith("TEST-")]
		settings.evo_lines = [r for r in settings.evo_lines if not r.instance_name.startswith("TEST-")]
		settings.save(ignore_permissions=True)
		frappe.db.commit()  # nosemgrep: frappe-manual-commit -- test fixture must be visible to later queries

	def test_duplicate_instance_name_rejected(self):
		_add_line("TEST-DUP")
		settings = frappe.get_single("Evolution API Settings")
		settings.append(
			"evo_lines",
			{"base_url": "https://evo2.example.com", "instance_name": "TEST-DUP", "api_key": "another-key"},
		)
		with self.assertRaises(frappe.ValidationError):
			settings.save(ignore_permissions=True)

	def test_webhook_secret_autogenerated_and_url_computed(self):
		_add_line("TEST-WEBHOOK")
		settings = frappe.get_single("Evolution API Settings")
		row = next(r for r in settings.evo_lines if r.instance_name == "TEST-WEBHOOK")
		self.assertTrue(row.webhook_secret)
		self.assertIn("frappe_whatsapp_evo.api.webhook", row.webhook_url)

	def test_find_line_missing_throws(self):
		with self.assertRaises(frappe.ValidationError):
			find_line("TEST-DOES-NOT-EXIST")

	def test_get_line_disabled_throws(self):
		_add_line("TEST-DISABLED", disabled=1)
		with self.assertRaises(frappe.ValidationError):
			get_line("TEST-DISABLED")

	def test_line_restriction_must_match_existing_instance_name(self):
		settings = frappe.get_single("Evolution API Settings")
		settings.append("line_restrictions", {"line": "TEST-NO-SUCH-LINE", "user": "Administrator"})
		with self.assertRaises(frappe.ValidationError):
			settings.save(ignore_permissions=True)

	def test_is_line_permitted_open_when_no_restrictions(self):
		_add_line("TEST-OPEN")
		self.assertTrue(is_line_permitted("TEST-OPEN", "someone@example.com"))

	def test_is_line_permitted_restricted(self):
		_add_line("TEST-RESTRICTED")
		_restrict_line("TEST-RESTRICTED", "Administrator")

		self.assertTrue(is_line_permitted("TEST-RESTRICTED", "Administrator"))
		self.assertFalse(is_line_permitted("TEST-RESTRICTED", "someone-else@example.com"))

	def test_get_available_lines_for_user_excludes_disabled_and_restricted(self):
		_add_line("TEST-AVAIL-OPEN")
		_add_line("TEST-AVAIL-DISABLED", disabled=1)
		_add_line("TEST-AVAIL-RESTRICTED")
		_restrict_line("TEST-AVAIL-RESTRICTED", "Administrator")

		available = get_available_lines_for_user("someone-else@example.com")
		self.assertIn("TEST-AVAIL-OPEN", available)
		self.assertNotIn("TEST-AVAIL-DISABLED", available)
		self.assertNotIn("TEST-AVAIL-RESTRICTED", available)

		available_for_admin = get_available_lines_for_user("Administrator")
		self.assertIn("TEST-AVAIL-RESTRICTED", available_for_admin)
